Home/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.urls')),
    path('sheti/', include('sheti.urls')),
    path('doctor/', include('doctor.urls')),
    path('chat/', include('chat.urls')),
    path('accounts/', include('account.urls')),
    path('admin/', admin.site.urls),
]

apps/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Contact(models.Model):
    name =models.CharField(max_length=50)
    phone_number =models.CharField(max_length=10)
    address =models.CharField(max_length=100,blank=True)


class Dairy(models.Model):
    sold=models.IntegerField()
    price=models.IntegerField()

class Collection(models.Model):
    title=models.CharField(max_length=100, unique=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title
class Collection_items(models.Model):
    name=models.CharField(max_length=60)
    quantity=models.CharField(max_length=15,null=True, blank=True)
    collection=models.ForeignKey(Collection, on_delete=models.DO_NOTHING,null=True, blank=True)

apps/templates/Index.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Ajax in one video - CodeWithHarry</title>
</head>

<body>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
        
        <h1>Ajax tutorial</h1>
    <button type="button" id="fetchBtn" class="btn btn-primary">Fetch Data</button>
    <button type="button" id="popBtn" class="btn btn-secondary">Populate</button>
    <form>
        username:<input type="text" id="username" value="user"><br>
        password:<input type="text" id="password" value="password321">
        <button type="button" id="login" class="btn btn-primary">Login</button>
    </form>
    <div class="container">
        <h1>Employee list</h1>
        <ul id="list">

        </ul>
    </div>
        <div id="myData"></div><br>
    
    <input type="text" id="collection">
    <button id="add_collection">Add Collection</button>

</body>
<script src="ajax.js"></script>
</html>

apps/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
      {% if user %}
      <a class="navbar-brand" href="#">{{user.username}}</a>
      {% else %}
      <a class="navbar-brand" href="#">Navbar</a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
          {% if user.is_authenticated%}
          <a class="nav-item nav-link active" href="{% url 'logout' %}">logout</a>
          <a class="nav-item nav-link active" href="{% url 'chat' %}">chat</a>
          <a class="nav-item nav-link active" href="{% url 'collection' %}">collection</a>
          <a class="nav-item nav-link active" href="{% url 'sheti_home' %}">Motor</a>
          {% else%}
          <a class="nav-item nav-link active" href="{% url 'register' %}">Register</a>
          <a class="nav-item nav-link active" href="{% url 'login' %}">Login</a>
          {% endif %}
          <a class="nav-item nav-link disabled" href="#">cooming soon..</a>
        </div>
      </div>
    </nav>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    {%block content%}
    {%endblock%}
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

apps/templates/collections.html
{% extends "base.html" %}

{% block content%}
<h1>Collections Page!</h1>
{{user.username}}
{% for c in collections%}
<div class="p-3 border bg-secondary">{{c.title}}  <a href="{% url 'collections' c.title %}"><button class="btn-sm btn-center">ADD</button></a></div>
{%for item in c.collection_items_set.all%}
  <div class="container">
    <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
      <div class="col"> 
        <a class="link-dark" onclick="return confirm('Delete {{item.name}} from {{c.title}}?');" href="{% url 'delete_item' item.id %}"><div class="p-3 border bg-light">{{item.name}} <br>{{item.quantity}}</div></a>
      </div>
    </div>
  </div>
  {%endfor%}
  {%endfor%}
{% endblock %}
\

apps/templates/create_collections.html
{% extends "base.html" %}

{% block content%}
<h1>Collection Page!</h1>
<h2>Add Items</h2>
{{user.username}}

<div class="container border">
{% if collection %}
{{collection}}
{% else %}
<select>
{% for collection in collections %}
<option value={{collection}}>{{collection}}</option>
{% endfor %}
</select>
{% endif %}
<form action="" method="post">
Item_name: <input type="text" name="name">
Quantity: <input type="text" name="quantity">
<input type="submit" value="Add">
</form>
</div>
{% endblock %}

apps/templates/home.html
{% extends "base.html" %}

{% block content%}
<h2>Home Page</h2>
<body bgcolor="green"></body>
{% endblock %}